nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-4.0.1.cjs

compressionLevel: mixed
enableGlobalCache: false
enableTelemetry: false
preferInteractive: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-tsconfig-references.cjs
    spec: 'https://github.com/Dcard/yarn-plugins/releases/latest/download/plugin-tsconfig-references.js'
